### ISSUE TITLE
No restore identifier for iOS 10 and Xcode 8.0

### ISSUE THREAD

**Issue by macinux** [Uepaa-AG/p2pkit-quickstart-ios#4] opened 2016-06-29 21:14 UTC
2016-06-29 17:11:31.193387 p2pkit-quickstart-ios[3017:1443320] [CoreBluetooth] API MISUSE: <private> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported

**Comment by thupa** [comment] 2016-06-30 07:35
Hi,
This issue is known to us and should not have any impact on the functional side.

The cause is the implementation of a delegate method without actually using the intended API.

Specifically, implementing the delegate: `centralManager:willRestoreState:` without using the StateRestoration API, hence the message: _Restoring will not be supported_ which is, in this case, by design.

If you would to `startP2PDiscoveryWithDiscoveryInfo:nil stateRestoration:YES`  the message will not appear.

If you don't object, we will close this issue, feel free to reopen.

Best

**Closed by thupa** 2016-06-30 07:35 UTC
